version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go-minor-patch:
        patterns: ['*']
        update-types: [minor, patch]
    labels:
      - dependencies
      - go

  - package-ecosystem: npm
    directory: /web/dashboard
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        patterns: ['*']
        update-types: [minor, patch]
    labels:
      - dependencies
      - npm
      - dashboard

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        patterns: ['*']
        update-types: [minor, patch]
    labels:
      - dependencies
      - npm
      - website

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        patterns: ['*']
        update-types: [minor, patch]
    labels:
      - dependencies
      - github-actions
